from pathlib import Path

# --- PATHS ---
DOCS_PATH = Path.home() / "Documents" / "DreamPlay"
DOCS_PATH.mkdir(parents=True, exist_ok=True)

# --- CONSTANTS ---
GRAPH_W, GRAPH_H = 400, 200
SECTION_H = GRAPH_H // 3
FONT_SCALE = 1.0
THICKNESS = 2
SCORE_FONT_SCALE = 1.5
SCORE_THICKNESS = 4

# --- STATE CONSTANTS ---
STATE_MENU = "MENU"
STATE_LOAD_PROFILE = "LOAD_PROFILE"
STATE_WAITING = "WAITING"
STATE_COUNTDOWN = "COUNTDOWN"
STATE_CALIBRATING = "CALIBRATING"
STATE_SAVE_PROMPT = "SAVE_PROMPT" # Kept for completeness/future use
STATE_SETTINGS = "SETTINGS"
STATE_ACTIVE = "ACTIVE"

# --- TRACKING CONSTANTS ---
LOST_TRACK_TIMEOUT = 0.5  # Seconds to "remember" a hand
CALIBRATION_DURATION = 3.0
COUNTDOWN_DURATION = 3.0
